FROM prom/prometheus

COPY config /etc/prometheus

#RUN apt install wget -y

#RUN wget https://github.com/prometheus/prometheus/releases/download/v3.5.0/prometheus-3.5.0.linux-amd64.tar.gz &&\
#    tar xvfz prometheus-3.5.0.linux-amd64.tar.gz

#ENTRYPOINT ["./prometheus-3.5.0.linux-amd64/prometheus", "--config.file=prometheus-3.5.0.linux-amd64/prometheus.yml"]

#EXPOSE 9090 



