{
 "title": "pong services dashboard",
 "description": "monitoring the pong app services",
 "time": { "from": "2025-12-22T14:24:37.439Z", "to": "2025-12-22T14:25:27.592Z" },
 "panels": [
  {
   "title": "Services status",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bool_on_off" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "up", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "HTTP request",
   "type": "stat",
   "description": "Total number of HTTP requests",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "req" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "http_requests_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total[5m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "expr": "process_resident_memory_bytes /  1024 / 1024",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}